collections:
  experiences:
      output: true
      permalink: /experiences/:title
  itineraries:
      output: true
      permalink: /itineraries/:title
  posts:
    output: true
    permalink: /posts/:title  
baseurl: ""
url: ""